//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProblemSolverApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229, 229, 229")]
        public global::System.Drawing.Color ControlBackground {
            get {
                return ((global::System.Drawing.Color)(this["ControlBackground"]));
            }
            set {
                this["ControlBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 204, 204")]
        public global::System.Drawing.Color ControlMenuBackground {
            get {
                return ((global::System.Drawing.Color)(this["ControlMenuBackground"]));
            }
            set {
                this["ControlMenuBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 127, 127")]
        public global::System.Drawing.Color ControlTitleBackground {
            get {
                return ((global::System.Drawing.Color)(this["ControlTitleBackground"]));
            }
            set {
                this["ControlTitleBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color MenuBackground {
            get {
                return ((global::System.Drawing.Color)(this["MenuBackground"]));
            }
            set {
                this["MenuBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 240, 240")]
        public global::System.Drawing.Color MainBackground {
            get {
                return ((global::System.Drawing.Color)(this["MainBackground"]));
            }
            set {
                this["MainBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("218, 218, 218")]
        public global::System.Drawing.Color ToolbarBackground {
            get {
                return ((global::System.Drawing.Color)(this["ToolbarBackground"]));
            }
            set {
                this["ToolbarBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180, 180, 180")]
        public global::System.Drawing.Color ToolbarColor {
            get {
                return ((global::System.Drawing.Color)(this["ToolbarColor"]));
            }
            set {
                this["ToolbarColor"] = value;
            }
        }
    }
}
